/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl

import org.eclipse.xtext.formatting2.IFormatter2
import org.xtext.example.mydsl.formatting2.MyDslFormatter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
//	override Class<? extends IFormatter2> bindIFormatter2() {
//		MyDslFormatter
//	}
}
